server:
  port: 8101

spring:
  rabbitmq:
    host: 172.18.86.45
    port: 5672
    username: admin
    password: admin
    publisher-confirms: true #消息发送到交换机确认机制，是否确认回调
    publisher-returns: true  #消息发送到交换机确认机制，是否返回回调
    listener:
      simple:
        acknowledge-mode: manual #采用手动应答
        concurrency: 1 #指定最小的消费者数量
        max-concurrency: 1 #指定最大的消费者数量
        default-requeue-rejected: false # 设置为false，会丢弃消息或者重新发布到死信队列
        retry:
          enabled: true # 允许消息消费失败的重试
          max-attempts: 3 # 消息最多消费次数
          initial-interval: 1000 # 消息多次消费的间隔秒
  redis:
    database: 0
    host: 172.18.86.37 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: founder # Redis服务器连接密码（默认为空）
    timeout: 5000 # 连接超时时间（毫秒）
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 8 # 连接池中的最小空闲连接