server:
  #服务端口号
  port: 8012

spring:
  application:
    name: applycore
  datasource:
      name: druidDataSource
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://172.18.86.37:3306/demo?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
      username: root
      password: root
      readSize: 1
      filters: stat,wall,log4j,config #配置扩展插件，常用的插件有=>stat:监控统计  log4j:日志  wall:防御sql注入
      max-active: 100  #最大连接池数量
      initial-size: 1  #初始化连接大小
      max-wait: 60000  #获取连接时最大等待时间，单位毫秒
      min-idle: 1      #最小连接池数量
      time-between-eviction-runs-millis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query: select 'x' #测试连接
      test-while-idle: true #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
      test-on-borrow: false #获取连接时执行检测，建议关闭，影响性能
      test-on-return: false #归还连接时执行检测，建议关闭，影响性能
      pool-prepared-statements: true #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20 #开启poolPreparedStatements后生效
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000 #通过connectProperties属性来打开mergeSql功能;慢SQL记录

mybatis:
  typeAliasesPackage: com.example.applycore.po
  mapperLocations: classpath:/mapper/*.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql