server:
  port: 8101

spring:
  rabbitmq:
    host: 172.18.86.45
    port: 5672
    username: admin
    password: admin
    publisher-confirms: true #消息发送到交换机确认机制，是否确认回调
    publisher-returns: true  #消息发送到交换机确认机制，是否返回回调
    listener:
      simple:
        acknowledge-mode: manual #采用手动应答
        concurrency: 1 #指定最小的消费者数量
        max-concurrency: 1 #指定最大的消费者数量
        default-requeue-rejected: false # 设置为false，会丢弃消息或者重新发布到死信队列
        retry:
          enabled: true # 允许消息消费失败的重试
          max-attempts: 3 # 消息最多消费次数
          initial-interval: 1000 # 消息多次消费的间隔秒
